# **Pandas**



1.   Pandas DataFrame
2.   Pandas Series
3.   Pandas Basic Operations



In [ ]:
# importing the library

import pandas as pd
import numpy as np

# Creating a data in a tabular format using numpy

In [ ]:
# creating a array using numpy
# np.arange(low, high, step_size)

# reshaping the array according to use
# np.arange(low, high, step_size).reshape(row, column)

np.arange(0, 20, 1).reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

# Intro to Pandas

When working with tabular data, such as data stored in spreadsheets or databases, pandas is the right tool for you. pandas will help you to explore, clean, and process your data. In pandas, a data table is called a `DataFrame`.

In [ ]:
# creating a Dataframe
df1 = pd.DataFrame(data = np.arange(0, 20).reshape(5, 4), index = ["Row1", "Row2", "Row3", "Row4", "Row5"], columns =["Column1", "Column2", "Column3", "Column4"])

In [ ]:
df1

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
df1["Column2"]

Row1     1
Row2     5
Row3     9
Row4    13
Row5    17
Name: Column2, dtype: int64

In [ ]:
type(df1)

pandas.core.frame.DataFrame

In [ ]:
# practice of ramdom function of numpy
# np.random.randint(low, high, size, dtype)


arr1 = np.random.randint(low = 10, high = 20, size = (5, 4))
arr1


array([[16, 16, 19, 11],
       [11, 19, 14, 18],
       [10, 14, 16, 14],
       [11, 16, 10, 16],
       [13, 12, 14, 12]])

In [ ]:
df2 = pd.DataFrame(data = arr1, index = ["Row1", "Row2", "Row3", "Row4", "Row5"], columns = ["Column1", "Column2", "Column3", "Column4"])

In [ ]:
df2

Column1  Column2  Column3  Column4
Row1       16       16       19       11
Row2       11       19       14       18
Row3       10       14       16       14
Row4       11       16       10       16
Row5       13       12       14       12

In [ ]:
# for watching the first 5 rows of the DataFrame, we can pass the parameter to see the specific number of datas of the DataFrame

df2.head()

Column1  Column2  Column3  Column4
Row1       16       16       19       11
Row2       11       19       14       18
Row3       10       14       16       14
Row4       11       16       10       16
Row5       13       12       14       12

In [ ]:
# To see the last 5 datas of the dataframe, we can give the parameter to see the specific number of data
df2.tail()

Column1  Column2  Column3  Column4
Row1       16       16       19       11
Row2       11       19       14       18
Row3       10       14       16       14
Row4       11       16       10       16
Row5       13       12       14       12

In [ ]:
arr2 = arr1.reshape(4, 5)
arr2

array([[16, 16, 19, 11, 11],
       [19, 14, 18, 10, 14],
       [16, 14, 11, 16, 10],
       [16, 13, 12, 14, 12]])

In [ ]:
df3 = pd.DataFrame(data = arr2)

In [ ]:
df3

0   1   2   3   4
0  16  16  19  11  11
1  19  14  18  10  14
2  16  14  11  16  10
3  16  13  12  14  12

In [ ]:
df3.rename(index ={0 : "Row1", 1: "Row2", 2: "Row3", 3: "Row4"}, inplace = True)

# if you use {inplace = True}, it will change the DataFrame permanantly

df3

0   1   2   3   4
Row1  16  16  19  11  11
Row2  19  14  18  10  14
Row3  16  14  11  16  10
Row4  16  13  12  14  12

In [ ]:
df3.rename(columns = {0: "Column1", 1:"Column2", 2: "Column3"})

Column1  Column2  Column3   3   4
Row1       16       16       19  11  11
Row2       19       14       18  10  14
Row3       16       14       11  16  10
Row4       16       13       12  14  12

In [ ]:
df3

0   1   2   3   4
Row1  16  16  19  11  11
Row2  19  14  18  10  14
Row3  16  14  11  16  10
Row4  16  13  12  14  12

In [ ]:
df3.rename(columns = {0: "Column1", 1: "Column2", 2: "Column3", 3: "Column4", 4: "Column5"}, inplace = True)

In [ ]:
df3

Column1  Column2  Column3  Column4  Column5
Row1       16       16       19       11       11
Row2       19       14       18       10       14
Row3       16       14       11       16       10
Row4       16       13       12       14       12

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int64
 1   Column2  5 non-null      int64
 2   Column3  5 non-null      int64
 3   Column4  5 non-null      int64
dtypes: int64(4)
memory usage: 372.0+ bytes


In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int64
 1   Column2  5 non-null      int64
 2   Column3  5 non-null      int64
 3   Column4  5 non-null      int64
dtypes: int64(4)
memory usage: 372.0+ bytes


In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Row1 to Row4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  4 non-null      int64
 1   Column2  4 non-null      int64
 2   Column3  4 non-null      int64
 3   Column4  4 non-null      int64
 4   Column5  4 non-null      int64
dtypes: int64(5)
memory usage: 364.0+ bytes


In [ ]:
df1.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [ ]:
df2.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean   12.200000  15.400000  14.600000  14.200000
std     2.387467   2.607681   3.286335   2.863564
min    10.000000  12.000000  10.000000  11.000000
25%    11.000000  14.000000  14.000000  12.000000
50%    11.000000  16.000000  14.000000  14.000000
75%    13.000000  16.000000  16.000000  16.000000
max    16.000000  19.000000  19.000000  18.000000

In [ ]:
df3.describe()

Column1    Column2    Column3    Column4    Column5
count     4.00   4.000000   4.000000   4.000000   4.000000
mean     16.75  14.250000  15.000000  12.750000  11.750000
std       1.50   1.258306   4.082483   2.753785   1.707825
min      16.00  13.000000  11.000000  10.000000  10.000000
25%      16.00  13.750000  11.750000  10.750000  10.750000
50%      16.00  14.000000  15.000000  12.500000  11.500000
75%      16.75  14.500000  18.250000  14.500000  12.500000
max      19.00  16.000000  19.000000  16.000000  14.000000

# Retriving the elements

we can retrive the elements using 3 methods


1.   using comlumn_index(slicing technique)
2.   using row_index(`loc` method)
3.   using row_column_index(`iloc` method)





In [ ]:
df1.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
df1["Column2"]

Row1     1
Row2     5
Row3     9
Row4    13
Row5    17
Name: Column2, dtype: int64

In [ ]:
type(df1["Column2"])

pandas.core.series.Series

In [ ]:
# when you are fetching more than one colum then use nested suared brackets

df1[["Column1", "Column2", "Column3"]]

Column1  Column2  Column3
Row1        0        1        2
Row2        4        5        6
Row3        8        9       10
Row4       12       13       14
Row5       16       17       18

In [ ]:
type(df1[['Column1', 'Column2', 'Column3']])

pandas.core.frame.DataFrame

In [ ]:
# retriving the rows using index_name method (loc[])
# we can get row and column as well but it need string indexers not numbric indexers
df1.loc["Row1"]

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int64

In [ ]:
type(df1.loc["Row1"])

pandas.core.series.Series

In [ ]:
df1.loc[["Row1", "Row2"]]

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7

In [ ]:
type(df1.loc[["Row1", "Row2"]])

pandas.core.frame.DataFrame

In [ ]:
df1.loc[["Row1", "Row2", "Row3"], ["Column1", "Column2"]]

Column1  Column2
Row1        0        1
Row2        4        5
Row3        8        9

In [ ]:
# Retriving the data using index and column number (.iloc method)

df1.iloc[0:3, 1:4]

Column2  Column3  Column4
Row1        1        2        3
Row2        5        6        7
Row3        9       10       11

In [ ]:
df1.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
df1.loc[["Row2", "Row3"], ["Column2", "Column3"]]

Column2  Column3
Row2        5        6
Row3        9       10

In [ ]:
# iloc requires numeric indexers

df1.iloc[1: 3, 1: 3]

Column2  Column3
Row2        5        6
Row3        9       10

In [ ]:
df1.iloc[:,:]

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
type(df1.iloc[1: 3, 1: 3])

pandas.core.frame.DataFrame

In [ ]:
df1.iloc[0,]

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int64

In [ ]:
type(df1.iloc[0,])

pandas.core.series.Series

In [ ]:
df1.iloc[:, :]

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
type(df1.iloc[: , :])

pandas.core.frame.DataFrame

In [ ]:
df1.iloc[:,0::3]

Column1  Column4
Row1        0        3
Row2        4        7
Row3        8       11
Row4       12       15
Row5       16       19

# Converting the DataFrame into array

we can convert the DataFrame into the array using .value method

In [ ]:
df1.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
df2.values

array([[16, 16, 19, 11],
       [11, 19, 14, 18],
       [10, 14, 16, 14],
       [11, 16, 10, 16],
       [13, 12, 14, 12]])

In [ ]:
pd.DataFrame(data = np.arange(0, 10).reshape(5, 2), index = ["Row1", "Row2", "Row3", "Row4", "Row5"], columns = ["Column1", "Column2"])

Column1  Column2
Row1        0        1
Row2        2        3
Row3        4        5
Row4        6        7
Row5        8        9

In [ ]:
pd.DataFrame(data = np.arange(0, 10).reshape(5, 2), index = ["Row1", "Row2", "Row3", "Row4", "Row5"], columns = ["Column1", "Column2"]).values

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# Basic Operations

basic operation on pandas